# Please refer to the https://prometheus.io/docs/prometheus/latest/configuration/configuration/ document to find more information about the configuration is this file
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: [ "otel-collector:8889" ]
      - targets: [ "otel-collector:8888" ]
