# Please refer to the https://opentelemetry.io/docs/collector/configuration/ document to find more information about the configuration is this file
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlphttp:
    endpoint: http://seq:5341/ingest/otlp

  otlp/aspire:
    endpoint: http://aspire-dashboard:18889
    tls:
      insecure: true

  otlp/elastic:
    endpoint: http://elastic_apm:8200
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, otlphttp, otlp/aspire, otlp/elastic ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus, otlp/aspire, otlp/elastic ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp, otlp/aspire, otlp/elastic ]
